name: Manually triggered workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Deploy to linode server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: |
          cd crypto-flash/
          export TG_CONFIG='${{ secrets.TG_CONFIG }}'
          echo $TG_CONFIG > config.json
          git fetch
          git checkout master
          git pull origin master
          export PATH=$PATH:/usr/local/go/bin
          go build -o main .
          sudo systemctl reload-or-restart crypto-flash

#     - name: Test
#       run: go test -v ./...
